' 参考URL
' https://future-architect.github.io/articles/20200203/

skinparam Actor {
    BackgroundColor black
    BorderColor black
}

skinparam Boundary {
    BackgroundColor white
    BorderColor 454645
    FontColor 454645
}

skinparam Entity {
    BackgroundColor white
    BorderColor 454645
    FontColor 454645
}

skinparam Control {
    BackgroundColor white
    BorderColor 454645
    FontColor 454645
}

skinparam Usecase {
    BackgroundColor white
    BorderColor 999999
}

skinparam BackgroundColor DDDDDD
skinparam shadowing false
skinparam RoundCorner 7
skinparam ArrowColor 454645
skinparam FontColor 454645