@startuml

usecase ログイン

actor ユーザー
boundary ログインページ
boundary #black ユーザー名入力ページ
control ログインページを表示する
control ユーザー名とパスワードを入力する
control アカウントは存在するか
control パスワードは正しいか
control #black ユーザー名またはパスワードが正くないを表示
control #black 3回目のログイン失敗か
control #black アカウントを凍結する
control #black 私のパスワードはリンクをクリックする
control #black ユーザー名入力ページを表示する
control #black ユーザーにパスワードをメールする
control アカウント情報を取得する1
control アカウント情報を取得する2
control 認証済みのセッションを開始する
control 歓迎メッセージとともに直前メッセージを再表示する
entity マスターアカウントリスト
entity アカウント1
entity アカウント2

ログインページを表示する --> ログインページ
ユーザー --> ログインページ
ログインページ --> ユーザー名とパスワードを入力する
ユーザー名とパスワードを入力する --> アカウントは存在するか : ログインボタンをクリック
アカウントは存在するか --> パスワードは正しいか : はい

パスワードは正しいか --> アカウント情報を取得する2
アカウント2 --> アカウント情報を取得する2
アカウント情報を取得する2 --> 認証済みのセッションを開始する
認証済みのセッションを開始する --> 歓迎メッセージとともに直前メッセージを再表示する

アカウントは存在するか --> ユーザー名またはパスワードが正くないを表示 : いいえ
アカウント1 --> アカウント情報を取得する1
アカウント情報を取得する1 --> マスターアカウントリスト
マスターアカウントリスト --> アカウントは存在するか

ユーザー名またはパスワードが正くないを表示 --> 3回目のログイン失敗か
アカウント1 -- アカウントを凍結する
アカウントを凍結する --> 3回目のログイン失敗か
3回目のログイン失敗か --> ログインページ

ログインページ --> 私のパスワードはリンクをクリックする
私のパスワードはリンクをクリックする --> ユーザー名入力ページを表示する
ユーザー名入力ページを表示する --> ユーザー名入力ページ
ユーザー名入力ページ --> ユーザーにパスワードをメールする

@enduml