@startuml
!include color.inc

商品.商品 "n" -- "1" カート.カート内商品
認証.ユーザ "1" ---- "1" カート.カート
商品カテゴリ.商品カテゴリ "n" -- "n" 商品.商品

 namespace 商品 {
   class 商品
 }
 商品.商品 : 商品ID
 商品.商品 : カテゴリID
 商品.商品 : レンタル料金

 namespace 商品カテゴリ {
   class 商品カテゴリ
 }
 商品カテゴリ.商品カテゴリ : 商品カテゴリID

 namespace カート {
   class カート
   class カート内商品
 }
 カート.カート : カートID
 カート.カート : ユーザID
 カート.カート内商品 : カート内商品ID
 カート.カート "1" *- "n" カート.カート内商品

 namespace 認証 {
   class ユーザ
   class SNSアカウント
 }
 認証.ユーザ : ユーザID
 認証.ユーザ "1" *- "n" 認証.SNSアカウント
@enduml