@startuml
!include color.inc

left to right direction
actor ログインユーザ
actor ゲスト

rectangle 宅配レンタル予約システム {
 package 認証 {
  package パスワードリセット {
   usecase リンク表示
   usecase リセット用メール送信
   usecase フォーム表示
   usecase パスワードリセット as 認証パスワードリセット
  }
  usecase SNSログイン
  usecase 会員ユーザ紐付け
  usecase 手動ログインフォーム表示
  usecase 手動ログイン
  usecase ユーザ登録フォーム表示
  usecase ユーザ登録
  usecase ログアウト
 }
 together {
 package 商品 {
  usecase 一覧表示 as 商品一覧表示
  usecase 登録 as 商品登録
  usecase 編集 as 商品編集
  usecase 詳細表示 as 商品詳細表示
 }
 package 商品カテゴリ {
  usecase 一覧表示 as 商品カテゴリ一覧表示
  usecase 登録 as 商品カテゴリ登録
 }
 package 特集 {
  usecase 一覧表示 as 特集一覧
  usecase 登録 as 特集登録
  usecase 詳細表示 as 特集詳細表示
 }
 together {
  package 注文 {
   usecase 注文を確定する
  }
  together {
   usecase メールを送信する
   package カート {
    usecase カートに入れる
    usecase カート内商品を削除
    usecase 一覧表示 as カート一覧
    usecase カート内商品を注文済みにする
   }
  }
 }
}
ログインユーザ ---> SNSログイン
ログインユーザ ---> 会員ユーザ紐付け
ログインユーザ ---> ログアウト
ログインユーザ ---> 商品一覧表示
ログインユーザ ---> 商品登録
ログインユーザ ---> 商品編集
ログインユーザ ---> 商品詳細表示
ログインユーザ ---> 商品カテゴリ一覧表示
ログインユーザ ---> 商品カテゴリ登録
ログインユーザ -> カートに入れる
ログインユーザ --> カート内商品を削除
ログインユーザ --> カート一覧
ログインユーザ ---> 注文を確定する
注文を確定する .> カート内商品を注文済みにする
注文を確定する ..> メールを送信する
ログインユーザ ---> 特集一覧
ログインユーザ ---> 特集登録
ログインユーザ ---> 特集詳細表示

SNSログイン <--- ゲスト
会員ユーザ紐付け <--- ゲスト
手動ログインフォーム表示 <--- ゲスト
手動ログイン <--- ゲスト
ユーザ登録フォーム表示 <--- ゲスト
ユーザ登録 <--- ゲスト
リンク表示 <--- ゲスト
リセット用メール送信 <--- ゲスト
フォーム表示 <--- ゲスト
認証パスワードリセット <--- ゲスト
商品一覧表示 <--- ゲスト
商品登録 <--- ゲスト
商品編集 <--- ゲスト
商品詳細表示 <--- ゲスト
@enduml