@startuml
!include color.inc

left to right direction
actor ログインユーザ
actor ゲスト

rectangle 宅配レンタル予約システム {
 package 認証 {
  package パスワードリセット {
   usecase リンク表示
   usecase リセット用メール送信
   usecase フォーム表示
   usecase パスワードリセット_
  }
  usecase SNSログイン
  usecase 会員ユーザ紐付け
  usecase 手動ログインフォーム表示
  usecase 手動ログイン
  usecase ユーザ登録フォーム表示
  usecase ユーザ登録
  usecase ログアウト
 }
 together {
 package 商品 {
  usecase 一覧表示
  usecase 登録
  usecase 編集
  usecase 詳細表示
 }
 package 商品カテゴリ {
  usecase 一覧表示_
  usecase 登録_
 }
 package 特集 {
  usecase 一覧表示___
  usecase 登録__
  usecase 詳細表示_
 }
 together {
  package 注文 {
   usecase 注文を確定する
  }
  together {
   usecase メールを送信する
   package カート {
    usecase カートに入れる
    usecase カート内商品を削除
    usecase 一覧表示__
    usecase 注文済みにする
   }
  }
 }
}
ログインユーザ ---> SNSログイン
ログインユーザ ---> 会員ユーザ紐付け
ログインユーザ ---> ログアウト
ログインユーザ ---> 一覧表示
ログインユーザ ---> 登録
ログインユーザ ---> 編集
ログインユーザ ---> 詳細表示
ログインユーザ ---> 一覧表示_
ログインユーザ ---> 登録_
ログインユーザ -> カートに入れる
ログインユーザ --> カート内商品を削除
ログインユーザ --> 一覧表示__
ログインユーザ ---> 注文を確定する
注文を確定する .> 注文済みにする
注文を確定する ..> メールを送信する
ログインユーザ ---> 一覧表示___
ログインユーザ ---> 登録__
ログインユーザ ---> 詳細表示_

SNSログイン <--- ゲスト
会員ユーザ紐付け <--- ゲスト
手動ログインフォーム表示 <--- ゲスト
手動ログイン <--- ゲスト
ユーザ登録フォーム表示 <--- ゲスト
ユーザ登録 <--- ゲスト
リンク表示 <--- ゲスト
リセット用メール送信 <--- ゲスト
フォーム表示 <--- ゲスト
パスワードリセット_ <--- ゲスト
一覧表示 <--- ゲスト
登録 <--- ゲスト
編集 <--- ゲスト
詳細表示 <--- ゲスト
@enduml