@startuml
!include color.inc

_集約ルート -[hidden]--> イベント履歴
イベント履歴 -[hidden]-> ログインユーザ
ログインユーザ -[hidden]-> トランザクション
トランザクション -[hidden]-> ID採番
ID採番 -[hidden]-> エロクアント拡張

package 共通 <<Folder>> {
  class エンティティ
  interface 集約ルート
  class ユニークキー
  class バリューオブジェクト
  class ドメインイベント
  class 仕様
  package 集約ルート as _集約ルート {
   class 集約ルートチェッカー
   interface 集約ルートチェッカーインターフェース
   class 集約ルートインスタンス例外
  }
  package イベント履歴 {
   class イベント履歴エロクアント
   class イベント履歴リポジトリ
  }
  package ログインユーザ {
   class ログインユーザ
   interface ログインユーザインターフェース
  }
  package トランザクション {
   class DBトランザクション
   interface トランザクションインターフェース
  }
  package ID採番 {
   class DBシーケンス
   interface ID採番インターフェース
  }
  package エロクアント拡張 {
   class 複合主キー設定
  }
}
@enduml