@startuml
!include color.inc

イベント履歴 -[hidden]-> ログインユーザ
ログインユーザ -[hidden]-> トランザクション
トランザクション -[hidden]-> ID採番

package 共通 <<Folder>> {
  class エンティティ
  class ユニークキー
  class バリューオブジェクト
  class ドメインイベント
  package イベント履歴 {
   class イベント履歴エロクアント
   class イベント履歴リポジトリ
  }
  package ログインユーザ {
   class ログインユーザ
   interface ログインユーザインターフェース
  }
  package トランザクション {
   class DBトランザクション
   interface トランザクションインターフェース
  }
  package ID採番 {
   class DBシーケンス
   interface ID採番インターフェース
  }
}
@enduml