@startuml
!include color.inc

actor プログラマ as pg
actor プロダクトオーナー as po

title 初回イテレーション(ゼロ)

group イテレーションゼロ
 group 計画ミーティング
    pg -> po : イテレーションを回すために\n必要なタスクを洗い出す
    pg -> po : プランニングポーカーでポイント付与
    po -> pg : 1週間でできる範囲でストーリーを選ぶ
    pg -> po : 完了条件を決める
 end

 group 開発する
    pg -> po : ストーリーの詳細を確認
    pg -> po : 必要なタスクを確認
    pg -> po : 受入条件を確認
    pg -> pg : 機能実装
    pg -> pg : 顧客テストの作成、実行
 end

 group デモ
    pg -> po : 変更した修正を報告
    pg -> po : 顧客テストの実行
    po -> pg : 要求の伝達ミスや漏れがないことを確認
    po -> pg : 完了を伝える
 end

 group ふりかえり
    pg -> pg : ふりかえりKPT
    pg -> pg : ベロシティの作成
    pg -> pg : 天気図の作成
 end

 group 次のイテレーションへ
 end

@enduml
