@startuml
!include color.inc

プレゼンテーション ---> アプリ
アプリ ---> ドメイン
ドメイン ---> インフラ

package 商品カテゴリ <<Folder>> {
 package プレゼンテーション {
  package ビューモデル {
   class 一覧ビューモデル
   class 詳細ビューモデル
  }
  package コントローラ {
   class 一覧コントローラ
   class 登録コントローラ
   class 詳細コントローラ
  }
 }
 package アプリ {
  package ユースケース {
   class 一覧表示クエリサービス
   interface 一覧表示クエリサービスインターフェース
   class 登録
   class 詳細表示クエリサービス
   interface 詳細表示クエリサービスインターフェース
  }
 }
 package ドメイン {
  package モデル {
   class 商品カテゴリ
   class 商品カテゴリID
   class 商品カテゴリファクトリ
   interface 商品カテゴリリポジトリインターフェース
  }
 }
 package インフラ {
  package レスポンスデータ {
   class 商品カテゴリIDレスポンスデータ
   class 商品カテゴリレスポンスデータ
   class 一覧表示クエリレスポンスデータ
   class 詳細表示クエリレスポンスデータ
  }
  package エロクアント {
   class 商品カテゴリエロクアント
  }
  package リポジトリ {
   class 一覧表示クエリサービス
   class 詳細表示クエリサービス
   class 商品カテゴリリポジトリ
  }
 }
}

@enduml