@startuml
!include color.inc

プレゼンテーション ---> アプリ
アプリ ----> ドメイン
ドメイン ----> インフラ

package 商品 <<Folder>> {
 package プレゼンテーション {
  package ビューモデル {
   class 一覧ビューモデル
   class 登録フォーム表示ビューモデル
   class 詳細ビューモデル
   class カテゴリ階層分割済みコレクション
  }
  package コントローラ {
   class 一覧コントローラ
   class 登録フォーム表示コントローラ
   class 登録コントローラ
   class 編集コントローラ
   class 詳細コントローラ
  }
 }
 package アプリ {
  package ユースケース {
   class 一覧表示
   interface 一覧表示クエリサービスインターフェース
   class 登録フォーム表示
   class 登録
   class 編集
   class 詳細表示
   interface 詳細表示クエリサービスインターフェース
  }
 }
 package ドメイン {
  namespace モデル {
   namespace アップロード {
    class ファイル
    interface 画像アップローダインターフェース
   }
   class カテゴリ
   class レンタル料金
   class 商品
   class 商品ID
   class 商品ファクトリ
   interface 商品リポジトリインターフェース
   interface 商品クエリサービスインターフェース
  }
 }
 package インフラ {
  namespace アップロード {
   class 画像アップローダ
  }
  package レスポンスデータ {
   class 商品IDレスポンスデータ
   class 商品レスポンスデータ
   class 商品カテゴリコレクションレスポンスデータ
   class 商品カテゴリレスポンスデータ
   class 商品画像コレクションレスポンスデータ
   class 商品画像レスポンスデータ
   class 一覧表示クエリレスポンスデータ
  }
  package エロクアント {
   class 商品エロクアント
   class 商品カテゴリエロクアント
   class 商品画像エロクアント
  }
  package リポジトリ {
   class 一覧表示クエリサービス
   class 商品リポジトリ
   class 商品クエリサービス
   class 詳細表示クエリサービス
  }
 }
}
@enduml