@startuml
!include color.inc

プレゼンテーション --> アプリ
アプリ --> ドメイン
ドメイン ----> インフラ

package カート <<Folder>> {
 package プレゼンテーション {
  package コントローラ {
   class 注文を確定するコントローラ
  }
 }
 package アプリ {
  package ユースケース {
   class メールを送信する
   class 注文を確定する
  }
 }
 package ドメイン {
  package モデル {
   class ユーザID
   class 商品ID
   class 注文
   interface 注文リポジトリインターフェース
   interface メールインターフェース
   class 注文ID
   class 注文ファクトリ
   class 注文明細
   class 注文が確定された時
  }
 }
 package インフラ {
  package メール {
   class メール
  }
  package レスポンスデータ {
   class 注文IDレスポンスデータ
  }
  package エロクアント {
   class 注文明細エロクアント
   class 注文エロクアント
  }
  package リポジトリ {
   class 注文リポジトリ
  }
 }
}
@enduml