@startuml
!include color.inc

プレゼンテーション ----> アプリ
アプリ ----> ドメイン
ドメイン --> インフラ

package 認証 <<Folder>> {
 package プレゼンテーション {
   package フォームリクエスト {
    class ユーザ登録フォームリクエスト
   }
  package コントローラ {
    package パスワードリセット {
     class リンク表示コントローラ
     class リセット用メール送信コントローラ
     class フォーム表示コントローラ
     class パスワードリセットコントローラ
    }
   class SNSログインコントローラ
   class 会員ユーザ紐付けコントローラ
   class 手動ログインフォーム表示コントローラ
   class 手動ログインコントローラ
   class ユーザ登録フォーム表示コントローラ
   class ユーザ登録コントローラ
   class ログアウトコントローラ
  }
 }
 package アプリ {
  namespace ユースケース {
    namespace パスワードリセット {
     class リンク表示
     class リセット用メール送信
     class フォーム表示
     class パスワードリセット
    }
   class SNSログイン
   class 会員ユーザ紐付け
   class 手動ログインフォーム表示
   class 手動ログイン
   class ユーザ登録フォーム表示
   class ユーザ登録
   class ログアウト
  }
 }
 package ドメイン {
  package モデル {
   class 会員ユーザ紐付けドメインサービス
   interface ドライバインターフェース
  }
 }
 package インフラ {
  package エロクアント {
   class ユーザエロクアント
   class SNSアカウントエロクアント
  }
  package ドライバ {
   package 追加SNS {
    class Amazonサービスプロバイダ
    class Amazonプロバイダ
   }
   class SNSドライバ
  }
 }
}
@enduml