@startuml
!include color.inc

package 実装 {
    actor 実装者
    (PRを作る)
note right
    * タイトルに「WIP {作業タスク}」を入力する
    * Reviewersにレビューワーを選択する
    * コメントにテンプレートにあわせて入力する
    * その他は入力不要
end note
実装者->(PRを作る)
(PRを作る)-->(実装中)
(実装中)-->(実装完了)
note right
    * コメント内のチェックを入れる。
    * タイトルを「レビュー待ち {作業タスク}」にする。
    * ChatWorkでレビュー依頼をする
         To レビューワー
         レビューお願いします。
         対象PRのURL
end note
}

package レビュー {
(実装完了)-->(レビューする)
レビューワー->(レビューする)
(レビューする)->(フィードバックする)
note right
    タイトル: フィードバック {作業タスク}
end note

(フィードバックする)->(実装中)
(レビューする)-->(開発ブランチへマージする)
}
@enduml
