name: Laravel

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Container
        run: |
          docker-compose down
          docker-compose build
          docker-compose up -d
      - name: Composer install
        run: docker exec app composer install
      - name: Reset database
        run: |
            docker-compose exec app php artisan migrate:fresh
            docker-compose exec app php artisan db:seed
      - name: PhpUnitTest
        run: docker-compose exec app php ./vendor/bin/phpunit

  deploy:
    needs: [laravel-tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          USER_NAME: ${{ secrets.USER_NAME }}
          HOST_NAME: ${{ secrets.HOST_NAME }}
          GIT_UESR_NAME: ${{ secrets.GIT_UESR_NAME }}
          GIT_PASS: ${{ secrets.GIT_PASS }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOST_NAME} "cd /home/ec2-user/www/takuhai-rental/ && git remote set-url origin http://${GIT_UESR_NAME}:${GIT_PASS}@github.com/nomura-kainos/takuhai-rental.git && git pull origin develop"